@extends("layouts.app")

@php
$is_jobs = true;
$job = $data["job"] ?? ""; 
$company = $data["company"] ?? ""; 
$questions = $data["questions"] ?? ""; 
use Carbon\Carbon;
@endphp

@section('title')
Automated Questions | HR
@endsection

@section("content")
<div class="jobs job_single">
	<x-main-nav></x-main-nav>

    <div class="section1">
        <h1 class="fw-bold mt-4 text-capitalize">{{$job->title}}</h1>
        <p class="fs-5 text-muted mt-3 mb-5">Discover your next career move, freelance gig, or internship</p>
    </div>
    
    <div class="section2 mb-5 d-flex flex-wrap">
        <div class="j_first">
           {{-- <div class="will_hid">
                <h4 class="fw-bold">Automated Questions</h4>
                <p class="text-muted t">You will go through an automated question-and-answer session, where questions are generated by AI based on the job description. This process helps ensure that the questions are relevant and tailored to assess your fit for the specific role. Please answer the questions to the best of your ability, as your responses will be used to evaluate your qualifications for the position.</p>
                <p class="text-muted fw-semibold mt-4 mb-2 ft">Please Note:</p>
                <ul class="text-danger">
                    <li class="text-danger mb-2 ft">Leaving this page will forfeit your scores, leading to 0 score.</li>
                    <li class="text-danger mb-2 ft">You have 15 minutes to complete all the answers.</li>
                    <li class="text-danger mb-2 ft">You will be redirected to the next page if your time runs out.</li>
                    <li class="text-danger mb-2 ft">Reloading the page will restart the timer and also generate new questions for you.</li>
                    <li class="text-danger mb-2 ft">Be sure of your answers.</li>
                </ul>
                <button class="btn-primary mt-2 btn px-4">Start</button>
                <p class="text-muted mt-2 mb-2 ft">Overall questions to be answer is 20.</p>
           </div> --}}

           <form action="" method="post">
                @csrf
                <div class="qst_ pt-4">
                    @foreach ($questions as $item)
                        <div class="mb-3">
                            <label class="text-muted fw-semibold ft" for="">{{$item}}</label>
                            <textarea name="" required id="" cols="3" rows="3"></textarea>
                        </div>                        
                    @endforeach
                </div>
                <button class="btn btn-primary px-4 mt-5">Save and Submit</button>                
            </form>
        </div>

        <div class="j_sec">
            <div class="__job__ mb-3">
                <h5 class="fw-bold mb-3">Recruiting?</h5>
                <p class="ft">Advertise your jobs to millions of monthly users and search 16.8 million CVs in our database.</p>
                <button class="btn btn-light mt-4">Post A Job</button>
            </div>
            <hr style="color: rgb(172, 172, 172)">

            <div class="d-flex pt-2" style="border-bottom: 1px solid rgb(235, 235, 235)">
                <img style="border-radius: 50%; object-fit:cover" width="30" height="30" src="{{$company->avatar}}" alt="">
                <p class="mb-3 mx-2 fw-bold text-capitalize"> <a class="text-decoration-none text-muted" href="/employer/{{$company->unique_id}}/{{str_replace(" ", "_", $company->company_name)}}">{{$company->company_name}}</a></p>
            </div>
            <p class="text-muted mt-3">We're looking to add more candidate to our growing teams.</p>
 
            <hr style="color: rgb(172, 172, 172)">
            <p class="fw-bold text-muted mb-1"><i class="fa-solid fa-bag-shopping"></i> Employment Type</p>
            <p class="mb-4 text-muted text-capitalize">{{$job->employment_type}}</p>

            <p class="fw-bold text-muted mb-1"><i class="fa-solid fa-location-dot"></i> Location</p>
            <p class="mb-4 text-muted text-capitalize">{{$job->state}}, {{$job->country}}</p>

            
            <p class="fw-bold text-muted mb-1">Level</p>
            <p class="mb-4 text-muted text-capitalize">{{$job->level}}</p>

            <p class="fw-bold text-muted mb-1"><i class="fa-solid fa-sack-dollar"></i> Salary</p>
            <p class="mb-4 text-muted">${{number_format($job->salary)}}</p>

            <p class="fw-bold text-muted mb-1"><i class="fa-regular fa-clock"></i> Date posted</p>
            <p class="mb-4 text-muted"> {{Carbon::create($job->created_at)->format('l F j, Y')}}</p>
            <hr style="color: rgb(172, 172, 172)">

            <p class="fw-bold text-muted mb-2">Contact Info</p>
            <p class="text-muted ft"><i class="fa-solid fa-phone"></i> {{$job->phone}}</p>
            <p class="text-muted ft"><i class="fa-regular fa-envelope"></i> {{$job->email}}</p>
            <p class="text-muted ft text-capitalize"><i class="fa-solid fa-location-dot"></i> {{$job->address}}</p>

        </div>
    </div>

	<hr style="color: rgb(183, 183, 183)">

    <div class="modal fade" id="apply__">
        <div class="modal-dialog modal-dialog-scrollable modal-dialog-centered">
          <div class="modal-content">
      
            <!-- Modal Header -->
            <div class="modal-header">
              <h6 class="modal-title">Job Application</h6>
              <button type="button" class="btn-close ft" data-bs-dismiss="modal"></button>
            </div>
      
            <!-- Modal body -->
            <div class="modal-body">
                <p class="fw-bold">Basic Information</p>
                <form action="/create-application" method="post" enctype="multipart/form-data">
                    @csrf
                    <input name="name" required type="text" placeholder="Enter fullname">
                    <input name="email" required type="email" placeholder="Enter email address">
                    <input name="phone" required type="text" placeholder="Phone number">
                    <input name="country" required type="text" placeholder="Country">
                    <input name="state" required type="text" placeholder="State">
                    <input name="city" required type="text" placeholder="city">
                    <input name="job_id" required type="text" class="d-none" value="{{$job->id}}">
                    <input name="company_id" required type="text" class="d-none" value="{{$company->id}}">
                    <input name="job_title" required type="text" class="d-none" value="{{$job->title}}">

                    <hr>
                    <p class="fw-bold">More Information</p>
                    <input required type="text" placeholder="Work title (eg) software developer, marketers, designer">
                    <input name="education" required type="text" placeholder="Education">
                    <input name="website" required type="text" placeholder="Portfolio website (link)">
                    <label for="__cv__" class="btn px-4 py-2 ft mt-3 mb-2" style="background-color: rgba(179, 179, 179, 0.266)">Upload Resume</label>
                    <input required accept=".pdf" type="file" name="company_logo" id="__cv__" class="d-none">
                    <p class="text-danger mb-2" style="font-size: 12px">Resume must be a (.pdf) file and must not be more than 5mb </p>
                    <input style="width: fit-content" type="submit" value="Apply" class="btn px-4 py-2 btn-primary mt-4 mb-5" >
                </form>

            </div>
      
            <!-- Modal footer -->
            <div class="modal-footer">
              <button type="button" class="btn px-4 btn-danger" data-bs-dismiss="modal">Close</button>
            </div>
      
          </div>
        </div>
    </div>

	<x-footer></x-footer>
</div>
@endsection